apiVersion: v1
kind: Pod
metadata:
  name: ros-teleop-pod-in-burger-32
spec:
  nodeName: turtlebot-bureger-3

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  containers:
    - name: turtlebot3-teleop-container
      image: ketidevit2/ros-humble-arm64:domain32.0.7
      imagePullPolicy: Always   # ARM64 노드에서 올바른 아키텍처 이미지 pull 보장
      command: ["/bin/bash", "-c", "tail -f /dev/null"]
      stdin: true
      tty: true

      env:
        - name: ROS_DOMAIN_ID
          value: "32"

        - name: ROS_DISCOVERY_SERVER
          value: "10.0.0.39:11811"

        # FastDDS 사용 명시
        - name: RMW_IMPLEMENTATION
          value: "rmw_fastrtps_cpp"

        # 로컬호스트만 사용하지 않음 (네트워크 통신 허용)
        - name: ROS_LOCALHOST_ONLY
          value: "0"

        # 디버깅을 위한 로깅 설정 (선택사항)
        - name: RCUTILS_LOGGING_USE_STDOUT
          value: "1"
        - name: RCUTILS_CONSOLE_OUTPUT_FORMAT
          value: "[{severity}] [{name}]: {message}"

  restartPolicy: Always
